dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
dotenv: .env
addresses:
  dot: ${BSC_DOT_ADDRESS}
  dot_owner: ${BSC_DOT_OWNER}
  feed: ${BSC_DOT_USD}
  multisig_wallet: ${MULTISIG_ADDRESS}
  account: ${PUBLIC_KEY}
  private_key: ${PRIVATE_KEY}
networks:
    default: ${DEFAULT_NETWORK}